apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: pv-test-nginx
  template:
    metadata:
      name: test
      labels:
        app: pv-test-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: cache-volume
              mountPath: /data
          resources:
            limits:
              cpu: '0.5m'
              memory: '500Mi'
      volumes:
        - name: cache-volume
          emptyDir: {}
